---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "openfaas-sqs-connector.labels" . | indent 4 }}
  name: {{ template "openfaas-sqs-connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}