---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-sqs-connector
  namespace: openfaas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfaas-sqs-connector
  name: openfaas-sqs-connector
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-sqs-connector
  template:
    metadata:
      labels:
        app: openfaas-sqs-connector
    spec:
      containers:
      - name: openfaas-sqs-connector
        image: form3tech/openfaas-sqs-connector:1.0.0
        args:
        - --log-level
        - "<log-level>"
        - --max-number-of-messages
        - "<max-number-of-messages>"
        - --max-wait-time
        - "<max-wait-time>"
        - --openfaas-gateway-url
        - "<openfaas-gateway-url>"
        - --queue-url
        - "<queue-url>"
        - --region
        - "<region>"
        - --topic-refresh-interval
        - "<topic-refresh-interval>"
        - --visibility-timeout
        - "<visibility-timeout>"
        env:
        - name: basic_auth
          value: "true"
        - name: secret_mount_path
          value: /secret
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - name: basic-auth
          readOnly: true
          mountPath: /secret
      securityContext:
        fsGroup: 65534
      serviceAccountName: openfaas-sqs-connector
      volumes:
      - name: basic-auth
        secret:
          secretName: basic-auth
